// AUTO-GENERATED by backend/scripts/start-with-tunnel.js — do not edit by hand.
// Overwritten every time `npm start` runs in backend/. Rebuild/reinstall the
// app (`flutter run`) after this changes, since it's a compiled-in const.
const String kApiBaseUrl = 'https://product-pry-sizably.ngrok-free.dev/api/v1';
